### PR TITLE
Setting names changed

### PR DESCRIPTION
**Pull request by RebornTrack970**
:/

### CODE REVIEW

**Comment by SMOLKEYS** [comment]
no because conflict and it took me forever to make this

**Comment by RebornTrack970** [comment]
> no because conflict and it took me forever to make this

yeah, i made it while you was making sorry. lol

**Comment by SMOLKEYS** [comment]
> > no because conflict and it took me forever to make this
> 
> yeah, i made it while you was making sorry. lol

k

**Comment by SMOLKEYS** [comment]
also i decided to check out the edits
_why is there 1 nsfw part_

**Comment by RebornTrack970** [comment]
Oh No

**Pull request closed without merging**
