### PR TITLE
Hi I am Derek Bum

### PR DESCRIPTION
**Pull request by MEEPofFaith**
why is this funny

### CODE REVIEW

**Review by WilloIzCitron — APPROVED** [review]
bruh The Kitchen Gun meme

**Comment by SMOLKEYS** [comment]
I- i dont even know at this point

**Comment by MEEPofFaith** [comment]
[KITCHEN GUN](https://youtu.be/6-7NDP8V-6A)
[KITCHEN GUN BUT DIFFERENT](https://youtu.be/f07xqTrD6jk)

**Comment by MEEPofFaith** [comment]
[TOILET GRENADE](https://youtu.be/t2UY_3RNggU)

**Pull request merged**
